Support modprobe in QEMU environment
I have modified scripts to make QEMU environment able to use modprobe for
inserting kernel modules.

In build-modules.sh, I attached make modules_install command and set
installed path to EXAMPLES_MOUNT_DIR, which is set in config.defaults.
The following QEMU boot process can mount this directory under /lib.
We also copied some necessary files from KERNEL_BUILD_DIR and
EXAMPLES_DIR for command 'depmod' usage.

For mounting installed module, we modify both init and boot.sh to
ensure that the path in host and QEMU are aligned

diff --git a/devtools/initramfs/init b/devtools/initramfs/init
--- a/devtools/initramfs/init
+++ b/devtools/initramfs/init
@@ -40,7 +40,13 @@ if [ -n "$TESTCMD" ]; then
     exit "$RESULT"
 fi
 
-# Interactive mode
+# Interactive mode with modprobe support
+mkdir -p /lib
+if ! mount -t 9p -o trans=virtio,version=9p2000.L lkmpg_modprobe /lib 2>/dev/null; then
+    echo "WARNING: 9p mount failed. /lib will be empty and modprobe is not working."
+    echo "Make sure QEMU was launched with -virtfs for lkmpg_modprobe."
+fi
+
 echo "================================================"
 echo "  lkmpg QEMU guest"
 echo "  Project:  /mnt/lkmpg/"
